### ISSUE TITLE
bug in unit test TestDeserializeWithBoundsElement()

### ISSUE THREAD

**Issue by cfrezksa** [OsmSharp/core#106]
In order for the unit test TestDeserializeWithBoundsElement() to work independent of culture, I suggest changing lines 200-204 in OsmTest.cs to 

            Assert.AreEqual(float.Parse("38.9070200", CultureInfo.InvariantCulture), osm.Bounds.MinLatitude);
            Assert.AreEqual(float.Parse("-77.0371900", CultureInfo.InvariantCulture), osm.Bounds.MinLongitude);
            Assert.AreEqual(float.Parse("38.9077300", CultureInfo.InvariantCulture), osm.Bounds.MaxLatitude);
            Assert.AreEqual(float.Parse("-77.0360000", CultureInfo.InvariantCulture), osm.Bounds.MaxLongitude);

**Comment by pietervdvn** [comment]
I searched for all instances of 'parse' with `grep -ir "Parse" .` in the root directory of the repository. I've only found a few relevant matches using `TryParse` which all already used the invariant-culture flag.

It seems like the unit tests have been refactored not using this anymore since the issue was opened  months ago.
