### ISSUE TITLE
Implement complete PBF write support

### ISSUE THREAD

**Issue by xivk** [OsmSharp/core#46]
Implement full PBF write support. OsmSharp only supports a simple (but compatible) version of the OSM PBF format. This leads to bigger files than expected.

**Comment by HarelM** [comment]
Hi,
Any updates on this?
I'm was hoping I could help out and try implement this, but it's a bit too complex for my understanding.
I tried to look at this code to see how serialization is done in osmosis:
https://github.com/openstreetmap/osmosis/blob/master/osmosis-pbf/src/main/java/crosby/binary/osmosis/OsmosisSerializer.java
and "compare" it to the following code:
https://github.com/OsmSharp/core/blob/develop/src/OsmSharp/IO/PBF/Encoder.cs
If my understanding is correct (which it's probably not) `Decode` takes a protobuf and changes it so that dense nodes are converted to nodes and later everything is converted to OsmGeo (not inside this method)
However, Encode doesn't convert the buffer from non dense to dense but rather fills the buffer, so this is a bit confusing - most of the code is symmetrical when it comes to conversion except these two functions.
If you have pointers that can guide me to the right approach I'm sure I can help a little to progress this.
I would like to replace OSM-C-Tools and use this code to manage my PBF file updates...

**Comment by HarelM** [comment]
I have looked through the code again, and I now think I fully understand it.
The only thing that I'm not sure about it the following comment - is it for performance sake?
https://github.com/OsmSharp/core/blob/e951c41f824aa4dc3afd79538ae29f3c1edf627a/src/OsmSharp/IO/PBF/Encoder.cs#L206
And it needs the following "if" as well...?
https://github.com/OsmSharp/core/blob/e951c41f824aa4dc3afd79538ae29f3c1edf627a/src/OsmSharp/IO/PBF/Encoder.cs#L225
In any case, adding EncodeDenseNode shouldn't be difficult now that I think I understand the code.
but removing this "if" and uncommenting the above comment would make the code much more simple, IMO.
@xivk let me know what you think and if you think this is the right course of action. 
Also, assuming I can send a pull request, could you create a pre-release NuGet package I can use?

**Comment by xivk** [comment]
I think because they get filled up and then later the one left over are removed here and yes probably for performance reasons. Not sure though, it's been a long time this code... 

If you send a pull-request implementing this then I'll make sure to create a package. :+1:  Also make sure to test the result with osmosis/JOSM or whatever other tools you are using. This gets pretty shaky and mistakes are easy to make. 

Thanks in advance for doing this!
