### ISSUE TITLE
How to put a new line in XML?

### ISSUE THREAD

**Issue by kitsukawa** [OsmSharp/core#75]
Hi,
I am writing a program which outputs xml file using OsmSharp. I managed to output necessary information to xml file. However, the all nodes/ways/relations are written in one line. Is it possible to output xml files which contains new line properly?

**Comment by xivk** [comment]
Unfortunately this is not something you can customize at this time. You can copy the code for the target stream:

https://github.com/OsmSharp/core/blob/master/src/OsmSharp/Streams/XmlOsmStreamTarget.cs#L48

And customize the XmlWriterSettings. I will leave this open, I'm considering adding support for this but it has to carefully thought out because it could break the osm-xml writer.

**Comment by kitsukawa** [comment]
Thank you very much for quick response. I understood that this is not supported at this time.
